CREATE DATABASE IF NOT EXISTS DRAGO;
USE DRAGO;

-- Entity/Table yang berdiri sendiri
CREATE TABLE IF NOT EXISTS Jabatan(
    ID_Jabatan BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nama_Jabatan VARCHAR(10) NOT NULL
)

CREATE TABLE IF NOT EXISTS Akun(
    ID_Akun BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nama VARCHAR(50) NOT NULL,
    Alamat VARCHAR(50) NOT NULL,
    Nomor_HP VARCHAR(20) NOT NULL,
    Username VARCHAR(20) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL,
    Sandi VARCHAR(255) NOT NULL,
    Status_Akun BOOLEAN DEFAULT TRUE,
    ID_Jabatan BIGINT UNSIGNED NOT NULL --fk
);

-- Penambahan Foreign Key
ALTER TABLE Akun
ADD CONSTRAINT fk_jabatan
FOREIGN KEY (ID_Jabatan)
REFERENCES Jabatan(ID_Jabatan);
